# Generated by Django 5.0.3 on 2024-03-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(0, 'unknown'), (1, 'critical'), (2, 'high'), (3, 'medium'), (4, 'low'), (99, 'obsolete')], default=0)),
            ],
        ),
    ]
